from __future__ import annotations

from p2p_engine.mcp.catalog import agents
from p2p_engine.mcp.catalog import collaboration
from p2p_engine.mcp.catalog import maintenance
from p2p_engine.mcp.catalog import project
from p2p_engine.mcp.catalog import project_readiness
from p2p_engine.mcp.catalog import prompts
from p2p_engine.mcp.catalog import proposals
from p2p_engine.mcp.catalog import vertical_registry
from p2p_engine.mcp.catalog import work_specs
from p2p_engine.mcp.catalog.prompts import PROMPT_TOOL_KINDS


TOOL_NAMES = (
    'p2p_init_project',
    'p2p_project_identity_show',
    'p2p_project_identity_status',
    'p2p_project_identity_transitions',
    'p2p_project_identity_copy_check',
    'p2p_project_identity_adopt_preview',
    'p2p_project_identity_adopt_apply',
    'p2p_project_identity_derive_preview',
    'p2p_project_identity_derive_apply',
    'p2p_agent_instructions_refresh',
    'p2p_agent_list',
    'p2p_agent_show',
    'p2p_agent_doctor',
    'p2p_agent_install',
    'p2p_agent_update',
    'p2p_agent_uninstall',
    'p2p_registry_refresh',
    'p2p_validate',
    'p2p_context',
    'p2p_assess_refresh',
    'p2p_assess_show',
    'p2p_project_domain_show',
    'p2p_project_domain_set',
    'p2p_project_domain_clear',
    'p2p_project_structure_show',
    'p2p_project_structure_history',
    'p2p_project_structure_export_eligibility',
    'p2p_project_structure_export_preview',
    'p2p_project_structure_replacement_inspect',
    'p2p_project_structure_replacement_preview',
    'p2p_project_structure_add_section',
    'p2p_project_structure_update_metadata',
    'p2p_project_structure_reorder_sections',
    'p2p_project_structure_retirement_preview',
    'p2p_project_structure_retirement_apply',
    'p2p_project_memory_classification',
    'p2p_proposal_scope_show',
    'p2p_proposal_scope_set',
    'p2p_project_rubrics_init',
    'p2p_project_rubrics_show',
    'p2p_maturity_refresh',
    'p2p_maturity_show',
    'p2p_proposal_create',
    'p2p_proposal_update',
    'p2p_proposal_contribution_add',
    'p2p_proposal_contribution_list',
    'p2p_intake_prompt',
    'p2p_intake_status',
    'p2p_project_brief_prompt',
    'p2p_project_brief_show',
    'p2p_choice_discover',
    'p2p_conflict_status',
    'p2p_governance_status',
    'p2p_governance_validate',
    'p2p_choice_governance_preflight',
    'p2p_vote_status',
    'p2p_precedent_search',
    'p2p_impact_prompt',
    'p2p_explore_import',
    'p2p_impact_import',
    'p2p_clarify_import',
    'p2p_synthesize_import',
    'p2p_plan_import',
    'p2p_tasks_import',
    'p2p_workspace_schema_status',
    'p2p_proposal_vertical_coverage_show',
    'p2p_proposal_vertical_coverage_suggest',
    'p2p_project_status',
    'p2p_project_progress',
    'p2p_project_freshness',
    'p2p_project_interaction_style_show',
    'p2p_project_interaction_style_set',
    'p2p_project_export',
    'p2p_project_export_status',
    'p2p_project_publish_prepare',
    'p2p_project_publish_import',
    'p2p_project_publish_validate',
    'p2p_project_publish_render',
    'p2p_project_publish_status',
    'p2p_project_publish_list',
    'p2p_project_vertical_list',
    'p2p_project_vertical_show',
    'p2p_project_vertical_validate',
    'p2p_project_vertical_select',
    'p2p_project_vertical_lock_show',
    'p2p_project_vertical_lock_repair',
    'p2p_vertical_domain_list',
    'p2p_vertical_domain_search',
    'p2p_vertical_domain_inspect',
    'p2p_vertical_release_list',
    'p2p_vertical_release_search',
    'p2p_project_context',
    'p2p_project_sections',
    'p2p_project_section_show',
    'p2p_project_definition_show',
    'p2p_project_definition_update',
    'p2p_project_readiness_review',
    'p2p_project_readiness_gaps',
    'p2p_project_readiness_gap_show',
    'p2p_project_questions_status',
    'p2p_project_questions_next',
    'p2p_next',
    'p2p_next_add',
    'p2p_next_complete',
    'p2p_next_retire',
    'p2p_next_refresh',
    'p2p_proposal_list',
    'p2p_proposal_show',
    'p2p_proposal_decision_status',
    'p2p_proposal_decision_history',
    'p2p_proposal_decision_impact',
    'p2p_proposal_decision_preview',
    'p2p_proposal_decision_apply',
    'p2p_proposal_decision_projection_repair_preview',
    'p2p_proposal_decision_projection_repair_apply',
    'p2p_proposal_decision_ledger_repair_preview',
    'p2p_proposal_decision_ledger_repair_apply',
    'p2p_proposal_readiness_get',
    'p2p_proposal_readiness_init',
    'p2p_proposal_readiness_refresh',
    'p2p_proposal_readiness_assess',
    'p2p_proposal_readiness_explain',
    'p2p_proposal_readiness_list_gaps',
    'p2p_proposal_readiness_review',
    'p2p_proposal_questions_status',
    'p2p_proposal_questions_init',
    'p2p_proposal_questions_add',
    'p2p_proposal_questions_answer',
    'p2p_proposal_questions_next',
    'p2p_proposal_questions_apply',
    'p2p_proposal_artifact_status',
    'p2p_proposal_artifact_init',
    'p2p_proposal_artifact_set',
    'p2p_proposal_artifact_confirm',
    'p2p_choice_list',
    'p2p_choice_show',
    'p2p_change_status',
    'p2p_change_show',
    'p2p_change_tasks',
    'p2p_work_list',
    'p2p_work_status',
    'p2p_work_show',
    'p2p_registry_status',
    'p2p_registry_show',
    'p2p_project_memory_status',
    'p2p_project_memory_show',
    'p2p_project_show',
    'p2p_permissions_show',
    'p2p_consent_request',
    'p2p_consent_status',
    'p2p_consent_show',
    'p2p_proposal_accept',
    'p2p_proposal_reject',
    'p2p_proposal_defer',
    'p2p_spec_lifecycle',
    'p2p_spec_status',
    'p2p_spec_show',
    'p2p_spec_export_status',
    'p2p_spec_export_show',
    'p2p_change_create',
    'p2p_project_refresh',
    'p2p_spec_refresh',
    'p2p_spec_export',
    'p2p_spec_export_validate',
    'p2p_work_plan',
    'p2p_explore_prompt',
    'p2p_digest_prompt',
    'p2p_clarify_prompt',
    'p2p_synthesize_prompt',
    'p2p_plan_prompt',
    'p2p_tasks_prompt',
    'p2p_swot_prompt',
    'p2p_spec_prompt',
)

def tool_definitions() -> list[dict[str, object]]:
    definitions = [
        *maintenance.tool_definitions(),
        *agents.tool_definitions(),
        *project.tool_definitions(),
        *vertical_registry.tool_definitions(),
        *project_readiness.tool_definitions(),
        *proposals.tool_definitions(),
        *collaboration.tool_definitions(),
        *work_specs.tool_definitions(),
        *prompts.tool_definitions(),
    ]
    definitions_by_name = {definition["name"]: definition for definition in definitions}
    if len(definitions_by_name) != len(definitions):
        raise RuntimeError("Duplicate MCP tool definition name")
    missing = [name for name in TOOL_NAMES if name not in definitions_by_name]
    if missing:
        raise RuntimeError(f"Missing MCP tool definitions: {missing}")
    extra = [name for name in definitions_by_name if name not in TOOL_NAMES]
    if extra:
        raise RuntimeError(f"Unexpected MCP tool definitions: {extra}")
    return [definitions_by_name[name] for name in TOOL_NAMES]
