from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import Protocol

from p2p_engine.core.decision_context import DecisionContextPacket
from p2p_engine.services.decision_context_rendering import render_nearby_decision_context


class RegistryStatusLike(Protocol):
    registries_dir: Path
    stale: bool
    proposals_count: int
    changes_count: int


class RegistryViewLike(Protocol):
    records: list[dict[str, object]]


class IntakeStatusLike(Protocol):
    intake_id: str
    status: str
    recommendation: str


def _read_optional(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


class ProjectContextRendererService:
    def __init__(
        self,
        *,
        p2p_dir: Path,
        show_registry: Callable[[str], RegistryViewLike],
        intake_statuses: Callable[[], list[IntakeStatusLike]],
    ) -> None:
        self.p2p_dir = p2p_dir
        self.show_registry = show_registry
        self.intake_statuses = intake_statuses

    def render_intake_context(
        self,
        registry_status: RegistryStatusLike,
        nearby_context: DecisionContextPacket | None = None,
    ) -> str:
        lines = [
            "# Intake Context",
            "",
            "## Registry Status",
            "",
            f"- Path: `{registry_status.registries_dir}`",
            f"- Stale: `{registry_status.stale}`",
            f"- Source proposals: {registry_status.proposals_count}",
            f"- Source changes: {registry_status.changes_count}",
            "",
        ]
        if nearby_context is None:
            lines.extend(
                [
                    "## Nearby Decision Context",
                    "",
                    "Not available for this renderer call. No registry-order fallback is used.",
                    "",
                ]
            )
        else:
            lines.append(
                render_nearby_decision_context(nearby_context, phase="intake").rstrip()
            )
            lines.append("")
        overview = _read_optional(self.p2p_dir / "project" / "overview.md")
        if overview:
            lines.extend(["## Project Overview", "", overview.strip(), ""])
        return "\n".join(lines)

    def render_project_brief_context(self, registry_status: RegistryStatusLike) -> str:
        lines = [
            "# Project Brief Context",
            "",
            "This context is generated by the CLI. Use it to write an operational synthesis, "
            "not to make governance decisions.",
            "",
            "## Registry Status",
            "",
            f"- Path: `{registry_status.registries_dir}`",
            f"- Stale: `{registry_status.stale}`",
            f"- Source proposals: {registry_status.proposals_count}",
            f"- Source changes: {registry_status.changes_count}",
            "",
        ]
        for registry_name in ("proposals", "changes", "choices", "decisions", "relations"):
            try:
                view = self.show_registry(registry_name)
            except ValueError:
                lines.extend([f"## {registry_name.title()} Registry", "", "Not generated yet.", ""])
                continue
            lines.extend([f"## {registry_name.title()} Registry", ""])
            if not view.records:
                lines.extend(["- None.", ""])
                continue
            for record in view.records[:50]:
                if registry_name == "proposals":
                    lines.append(
                        f"- {record.get('id')}: {record.get('status')} - {record.get('title')}"
                    )
                elif registry_name == "changes":
                    included = record.get("included_proposals", [])
                    included_text = ", ".join(str(item) for item in included) if isinstance(included, list) else ""
                    lines.append(
                        f"- {record.get('id')}: {record.get('status')} - "
                        f"{record.get('title')} (proposals: {included_text or 'none'})"
                    )
                elif registry_name == "choices":
                    selected = record.get("selected_option") or "not decided"
                    lines.append(
                        f"- {record.get('id')}: {record.get('status')} - "
                        f"{record.get('title')} -> {selected}"
                    )
                elif registry_name == "decisions":
                    lines.append(
                        f"- {record.get('proposal')}: {record.get('outcome')} - "
                        f"{record.get('title')}"
                    )
                else:
                    lines.append(
                        f"- {record.get('source')} -> {record.get('target')} ({record.get('type')})"
                    )
            lines.append("")

        project_files = {
            "Project Overview": self.p2p_dir / "project" / "overview.md",
            "Project Scope": self.p2p_dir / "project" / "scope.md",
            "Project Conflicts": self.p2p_dir / "project" / "conflicts.yml",
        }
        for title, path in project_files.items():
            content = _read_optional(path)
            if content:
                lines.extend([f"## {title}", "", content.strip(), ""])

        intake_statuses = self.intake_statuses()
        lines.extend(["## Intake Status", ""])
        if intake_statuses:
            for status in intake_statuses:
                lines.append(f"- {status.intake_id}: {status.status} - {status.recommendation}")
        else:
            lines.append("- None.")
        lines.append("")
        return "\n".join(lines)
